# Generated by Django 4.2 on 2026-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimentAlumnat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_i_cognom', models.CharField(blank=True, max_length=255, null=True)),
                ('cognom1', models.CharField(blank=True, max_length=120, null=True)),
                ('cognom2', models.CharField(blank=True, max_length=120, null=True)),
                ('nom', models.CharField(blank=True, max_length=120, null=True)),
                ('document', models.CharField(blank=True, max_length=32, null=True)),
                ('sexe', models.CharField(blank=True, max_length=20, null=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('correu', models.EmailField(blank=True, max_length=254, null=True)),
                ('bc', models.CharField(blank=True, max_length=50, null=True)),
                ('cj', models.CharField(blank=True, max_length=50, null=True)),
                ('cg', models.CharField(blank=True, max_length=50, null=True)),
                ('pa', models.CharField(blank=True, max_length=50, null=True)),
                ('mdp', models.CharField(blank=True, max_length=50, null=True)),
                ('ropec', models.CharField(blank=True, max_length=50, null=True)),
                ('estat', models.CharField(blank=True, max_length=50, null=True)),
                ('notificacio', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seguiment Alumnat',
                'db_table': 'seguiment_alumnat',
            },
        ),
    ]
